Attach the route summarization policy under L3Out Ext EPG
netascode/terraform-aci-nac-aci pull request #120
Opened 2024-07-26 12:19 UTC by devegupt

Adding support to attach the route summarization policy under L3Out External EPG Subnet

2024-07-29 00:01 UTC, andbyrne commented
This appears to be a breaking change. The original schema should be retained, and continue to apply the default policy from the common tenant if no policy is specified in the new `bgp_route_summarization_policy` attribute.

2024-07-29 04:42 UTC, devegupt commented
> This appears to be a breaking change. The original schema should be retained, and continue to apply the default policy from the common tenant if no policy is specified in the new `bgp_route_summarization_policy` attribute.

Sounds good, I am working on this.

2024-07-29 10:59 UTC, devegupt commented
> This appears to be a breaking change. The original schema should be retained, and continue to apply the default policy from the common tenant if no policy is specified in the new `bgp_route_summarization_policy` attribute.

I have pushed the updates in this PR. As per the new logic:

1. If "bgp_route_summarization" is set to 'true' and "bgp_route_summarization_policy" is not defined, 'default' route summarization policy will be added.
2. If "bgp_route_summarization" is set to 'true' and "bgp_route_summarization_policy" is defined, custom policy name will be added.
3. If "bgp_route_summarization" is set to 'false' and "bgp_route_summarization_policy" is defined, no policy will be added.
4. If "bgp_route_summarization" is set to 'false' and "bgp_route_summarization_policy" is not defined, no policy will be added.

2024-07-29 16:07 UTC, juchowan requested changes

2024-07-29 16:07 UTC, juchowan commented on modules/terraform-aci-external-endpoint-group/variables.tf
> +    bgp_route_summarization_policy = string
should be optional

2024-07-29 16:30 UTC, devegupt commented on modules/terraform-aci-external-endpoint-group/variables.tf
> +    bgp_route_summarization_policy = string
Good catch, fixed.

2024-07-29 16:41 UTC, devegupt commented
> This appears to be a breaking change. The original schema should be retained, and continue to apply the default policy from the common tenant if no policy is specified in the new `bgp_route_summarization_policy` attribute.

done

2024-07-30 08:12 UTC, juchowan requested changes

2024-07-30 08:12 UTC, juchowan commented on modules/terraform-aci-external-endpoint-group/variables.tf
> +    bgp_route_summarization_policy = optional(string)
with the default "" value

2024-07-30 08:15 UTC, juchowan commented
please also run pre-commit

2024-07-30 11:30 UTC, devegupt commented on modules/terraform-aci-external-endpoint-group/variables.tf
> +    bgp_route_summarization_policy = optional(string)
fixed

2024-07-30 11:30 UTC, devegupt commented
> please also run pre-commit

Done

2024-07-30 15:03 UTC, merged