Add Data Plane Policing Policy module
netascode/terraform-aci-nac-aci pull request #147
Opened 2024-09-12 19:35 UTC by therealdoug

A: aci-data-plane-policing-policy
M: aci-access-leaf-interface-policy-group
M: aci-endpoint-group
M: aci-l3out-interface-profile
M: aci_access_policies.tf
M: aci_tenants.tf
M: defaults.yaml
M: modules.yaml

2024-09-12 19:42 UTC, therealdoug commented
@juchowan   ready for review

This replaces #131 because my source tree got messed up.

2025-04-04 14:06 UTC, juchowan requested changes
Hi @therealdoug, thanks for contribution! It took a while to review pending PRs, an we require some changes here. Would you still like to work on this PR?

2025-04-04 14:06 UTC, juchowan commented on defaults/defaults.yaml
> +          pir: 0
same in tenant policies for pir and pir_unit

2025-04-04 14:06 UTC, juchowan commented on modules/terraform-aci-access-leaf-interface-policy-group/main.tf
> +  count      = var.type != "breakout" ? 1 : 0
should include checking if its breakout and if the policy is specified, if not, we don't want to deploy that resource at all

2025-04-04 14:06 UTC, juchowan commented on modules/terraform-aci-access-leaf-interface-policy-group/main.tf
> +  count      = var.type != "breakout" ? 1 : 0
should include checking if its breakout and if the policy is specified, if not, we don't want to deploy that resource at all

2025-04-04 14:06 UTC, juchowan commented on modules/terraform-aci-data-plane-policing-policy/.terraform-docs.yml
> +  # Terraform ACI Access Data Plane Plane Policing Module
if we are using one module for both access and tenant configuration than decsription can be just Data Plane Policing Module

2025-04-04 14:06 UTC, juchowan commented on modules/terraform-aci-data-plane-policing-policy/.terraform-docs.yml
> +  Manages Access Data Plane Policing Policies
And here we can add this twice to indicate that we can configure it both for access and tenant

2025-04-04 14:06 UTC, juchowan commented on modules/terraform-aci-endpoint-group/main.tf
> +  dn         = "${aci_rest_managed.fvAEPg.dn}/rsdppPol"
i think  we're missing count here

2025-04-04 14:06 UTC, juchowan commented on modules/terraform-aci-l3out-interface-profile/main.tf
> +  dn         = "${aci_rest_managed.l3extLIfP.dn}/rsegressQosDppPol"
and we're missing count in both these resources

2025-04-07 13:30 UTC, therealdoug commented
Thanks for the feedback!  Update submitted for requested changes.

2025-04-08 13:03 UTC, juchowan requested changes

2025-04-08 13:03 UTC, juchowan commented on modules/terraform-aci-data-plane-policing-policy/main.tf
> +    peak_rate       = var.type == "2R3C" ? var.peak_rate : null
thats the only place in the module where we need to keep pir and pirUnit as this is what ACI API expects, we only want to swap it on our side in data models and internal variables

2025-04-08 13:03 UTC, juchowan commented on modules/terraform-aci-data-plane-policing-policy/.terraform-docs.yml
> +  `Fabric` » `Access Policies` » `Policies` » `Interface` » `Data Plane Policing`
please add the other location under Tenant how to create it

2025-09-25 11:58 UTC, merged