Update README.md
netascode/terraform-aci-nac-aci pull request #76
Opened 2024-04-18 11:34 UTC by mthurstocisco

update to documentation based on changes here
https://wwwin-github.cisco.com/netascode/aac/pull/337

2024-05-07 10:01 UTC, moskrive requested changes
Additional code changes in the Terraform module to enable routed domains without a VLAN pool associate.

These ares includes:

- aci_access_policies.tf script to make the VLAN pool attribute optional and only provided it if defined
- terraform-aci-routed-domain sub module to the VLAN pool optional in the terraform code and configure the VLAN pool reference object when defined

2024-05-23 12:55 UTC, mthurstocisco commented
@danischm  @moskrive think this is what was requested, please let me know if anything else is required

2024-05-24 13:42 UTC, moskrive approved these changes

2024-05-25 05:56 UTC, danischm approved these changes

2024-05-25 05:56 UTC, merged